### ISSUE TITLE
"Not a valid npm package"

### ISSUE THREAD

**Issue by robertmaxton42** [ryantam626/jupyterlab_sublime#1]
`jupyter labextension install @ryantam6267/jupyterlab_sublime` tries to find `@ryantam6267/jupyterlab_sublime@latest`, can't find it (404 Not Found), and errors with 
`ValueError: "@ryantam6267/jupyterlab_sublime" is not a valid npm package`

Any idea what that's about?

(I'm really hoping this works, because I _really_ miss Ctrl-D in particular...

**Comment by ryantam626** [comment]
You got an extra `7` there :wink:
> because I really miss Ctrl-D in particular...
Hahaha this is _exactly_ why I made this!

**Comment by robertmaxton42** [comment]
... god dammit, there's a smudge on my screen right next to where the slash appears on your install instructions and I misread it as a 7....

Fixed. Thanks. >>>

**Comment by ryantam626** [comment]
Happens to the best of us haha :see_no_evil: 

Closing the issue now :+1:
