### ISSUE TITLE
No Alt-F3 (Windows or Linux) or Command+Ctrl+G (Mac OS X) to highlight every instance of the word in the document?

### ISSUE THREAD

**Issue by rightx2** [ryantam626/jupyterlab_sublime#10]
Any plan to introduce 'highlighting every instance of the word in the document'?

**Comment by ryantam626** [comment]
hi terribly sorry for missing this completely!!

i am surprised this doesn't work out of the box, it's part of what's available in the default keymap in codemirror's sublime keymap.

**Comment by rightx2** [comment]
Still not supported?

**Comment by ryantam626** [comment]
just tested it myself after installing my plugin again just for this (i don't use sublime keybinds anymore)
it works for me. there must be something on your system that's intercepting the `Alt-F3` combo

**Comment by ryantam626** [comment]
![Selection_009](https://user-images.githubusercontent.com/8895126/80692425-74271780-8ac9-11ea-9f28-24bb54f212bb.png)

**Comment by ryantam626** [comment]
Any news? If not I would like to close this issue :smile:
