### ISSUE TITLE
incompatibility with jupyterlab 2.0

### ISSUE THREAD

**Issue by krlng** [ryantam626/jupyterlab_sublime#11]
sadly the plugin as not does not work with the most recent jupyterlab version, required changes are documented here: https://jupyterlab.readthedocs.io/en/stable/developer/extension_migration.html

**Comment by ryantam626** [comment]
will publish a new version soon :+1:

**Comment by ryantam626** [comment]
published - `jupyter labextension install @ryantam626/jupyterlab_sublime@0.3.0` should do the trick.

**Comment by krlng** [comment]
Works like a charm, thanks for the quick fix
