### ISSUE TITLE
Do not support jupyter lab 2.1

### ISSUE THREAD

**Issue by bsun0802** [ryantam626/jupyterlab_sublime#15]
Hi Author,

Great thanks for your creation of this extension. Any plan on support jupyter lab 2.1?

**Comment by ryantam626** [comment]
I just tested with `jupyterlab==2.1.2` and it seems to work?

What issue are you seeing?

**Comment by bsun0802** [comment]
Thanks, I re-installed jupyter lab and it seems working.
