### ISSUE TITLE
Compatibility with JuypterLab 3.0

### ISSUE THREAD

**Issue by krlng** [ryantam626/jupyterlab_sublime#19]
JupyterLab 3.0 is available. The migration guide is here: https://jupyterlab.readthedocs.io/en/latest/extension/extension_migration.html

**Comment by hoishing** [comment]
hope the next update could use the pre-build feature of jupyterlab 3, thanks 🙏

**Comment by justinessert** [comment]
I really enjoy this package, would also very much appreciate a version compatible with Jupyterlab 3. Thank you!!

**Comment by ryantam626** [comment]
A little gratitude would go a long way :wink: 

I published 0.4.1 which should address this. I don't use this package anymore, so I don't actively work on this myself. (i.e. please test and let me know if something is wrong)

**Comment by krlng** [comment]
Works like a charm. Thanks for still maintaining the library, even that you don't use it - I ❤️ it
