### ISSUE TITLE
New version for latest version

### ISSUE THREAD

**Issue by robertmaxton42** [ryantam626/jupyterlab_sublime#5]
Any way we could get a new version for jupyterlab 0.18? Hopefully there shouldn't be much in the way of actual changes necessary, but as it is it's not possible to, say, run this and also [jupyterlab/git](https://github.com/jupyterlab/jupyterlab-git) or [jupyterlab/latex](https://github.com/jupyterlab/jupyterlab-latex) thanks to mutually exclusive version requirements.

Thanks!

**Comment by ryantam626** [comment]
Hmm that's weird, the requirements is quite lax already, https://github.com/ryantam626/jupyterlab_sublime/blob/58a8e5190bdb6e6c73d18b305f1f6bd9c8d66a15/package.json#L33-L34

Can you post any errors that you are seeing please?

**Comment by robertmaxton42** [comment]
Hm, I seem to have somehow gotten an older version. Updating solved the problem. Thanks!

**Comment by ryantam626** [comment]
Good to hear! :+1: Closing this issue for now :grinning:
