### ISSUE TITLE
ESC handling in console mode switches to an open notebook

### ISSUE THREAD

**Issue by narfanar** [ryantam626/jupyterlab_sublime#6]
Is there any mechanism to choose some shortcuts to keep or no?

Pressing ESC while in a console right now attempts to go to some open notebook instead, which is very distracting (even though ESC doesn't actually do anything in console mode in vanilla Jupyter Lab, yet).

**Comment by ryantam626** [comment]
Hi! There is no pmechanism to choose some shortcuts that I know of at the moment.

With that said, I released a new version which contain a fix for the issue that you mentioned which actually mistakenly affects all CodeMirror using component in jupyterlab.

Let me know if it still doesn't work for you :+1: Closing this for now.
