### ISSUE TITLE
Accel maps to Ctrl on windows

### ISSUE THREAD

**Issue by jasongrout** [ryantam626/jupyterlab_sublime#7]
Cool extension! I noticed in a few places you conditionally used Accel vs Ctrl for mac vs windows. Accel maps to Command on mac, but to Ctrl on Windows, so I think you don't need to split the logic. Just use Accel and it will be Ctrl on windows automatically.

See https://github.com/ryantam626/jupyterlab_sublime/blob/6813490d11d5df24ed453cb020885217294bed30/src/index.ts#L78 and https://github.com/ryantam626/jupyterlab_sublime/blob/6813490d11d5df24ed453cb020885217294bed30/src/index.ts#L84, for example. I think there is one other place too.

**Comment by ryantam626** [comment]
Ah thanks! I wasn't aware of this since I personally just use Linux. Will fix that soon :+1:
